linters:
  enable:
    - maligned
    - deadcode
    - errcheck
    - gosec
    - goconst
    - gocyclo
    - gofmt
    - golint
    - ineffassign
    - interfacer
    - staticcheck
    - structcheck
    - unconvert
    - varcheck
    - vet
    - vetshadow